/** Common disposable / throwaway email domains. */
export const DISPOSABLE_DOMAINS = new Set<string>([
  "10minutemail.com",
  "guerrillamail.com",
  "mailinator.com",
  "tempmail.com",
  "temp-mail.org",
  "throwawaymail.com",
  "yopmail.com",
  "getnada.com",
  "trashmail.com",
  "fakeinbox.com",
  "sharklasers.com",
  "dispostable.com",
  "maildrop.cc",
  "mintemail.com",
  "mailnesia.com",
  "spam4.me",
  "mohmal.com",
  "emailondeck.com",
  "tempr.email",
  "discard.email",
]);

/** Role-based local parts that are usually shared inboxes, not people. */
export const ROLE_PREFIXES = new Set<string>([
  "admin",
  "administrator",
  "billing",
  "contact",
  "help",
  "hello",
  "hr",
  "info",
  "marketing",
  "noreply",
  "no-reply",
  "office",
  "postmaster",
  "sales",
  "security",
  "support",
  "team",
  "webmaster",
  "abuse",
  "careers",
  "jobs",
]);

/** Free public mailbox providers — valid, but lower-value B2B leads. */
export const FREE_PROVIDERS = new Set<string>([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "ymail.com",
  "outlook.com",
  "hotmail.com",
  "live.com",
  "msn.com",
  "icloud.com",
  "me.com",
  "aol.com",
  "proton.me",
  "protonmail.com",
  "gmx.com",
  "zoho.com",
  "mail.com",
  "yandex.com",
]);
